CREATE TABLE outbox_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id TEXT COLLATE "C" NOT NULL CHECK (octet_length(event_id) BETWEEN 1 AND 128),
    aggregate_type TEXT COLLATE "C" NOT NULL CHECK (octet_length(aggregate_type) BETWEEN 1 AND 128),
    aggregate_id TEXT COLLATE "C" NOT NULL CHECK (octet_length(aggregate_id) BETWEEN 1 AND 190),
    event_type TEXT COLLATE "C" NOT NULL CHECK (octet_length(event_type) BETWEEN 1 AND 128),
    payload BYTEA NOT NULL,
    traceparent TEXT COLLATE "C" CHECK (octet_length(traceparent) BETWEEN 1 AND 64),
    tenant TEXT COLLATE "C" NOT NULL DEFAULT 'system' CHECK (octet_length(tenant) BETWEEN 1 AND 256),
    channel TEXT COLLATE "C" NOT NULL DEFAULT 'global' CHECK (octet_length(channel) BETWEEN 1 AND 64),
    dispatched BOOLEAN NOT NULL DEFAULT FALSE,
    attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    dead BOOLEAN NOT NULL DEFAULT FALSE,
    dead_at_ms BIGINT CHECK (dead_at_ms >= 0),
    created_at_ms BIGINT NOT NULL DEFAULT (FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000)::BIGINT)
        CHECK (created_at_ms >= 0),
    dispatched_at_ms BIGINT CHECK (dispatched_at_ms >= 0),
    CONSTRAINT outbox_event_event_id_key UNIQUE (event_id),
    CHECK (NOT dispatched OR NOT dead)
);

CREATE INDEX outbox_dispatchable_idx ON outbox_event (id) WHERE NOT dispatched AND NOT dead;
CREATE INDEX outbox_lane_dispatchable_idx ON outbox_event (channel, id) WHERE NOT dispatched AND NOT dead;
CREATE INDEX outbox_tenant_dispatchable_idx ON outbox_event (tenant, id) WHERE NOT dispatched AND NOT dead;
CREATE INDEX outbox_dead_idx ON outbox_event (id) WHERE dead;
CREATE INDEX outbox_retention_dispatched_idx ON outbox_event (dispatched_at_ms, id)
    WHERE dispatched AND NOT dead;
CREATE INDEX outbox_retention_dead_idx ON outbox_event (dead_at_ms, id) WHERE dead;

CREATE TABLE outbox_dispatch_owner (
    owner_role TEXT COLLATE "C" NOT NULL CHECK (octet_length(owner_role) BETWEEN 1 AND 32),
    lane TEXT COLLATE "C" NOT NULL CHECK (octet_length(lane) BETWEEN 1 AND 64),
    owner_id TEXT COLLATE "C" NOT NULL CHECK (octet_length(owner_id) BETWEEN 1 AND 64),
    fencing_token BIGINT NOT NULL CHECK (fencing_token > 0),
    lease_until_ms BIGINT NOT NULL CHECK (lease_until_ms >= 0),
    CONSTRAINT outbox_dispatch_owner_pkey PRIMARY KEY (owner_role, lane)
);
CREATE INDEX outbox_dispatch_owner_lease_idx ON outbox_dispatch_owner (lease_until_ms, owner_role, lane);

CREATE TABLE outbox_tenant_quota (
    tenant_id TEXT COLLATE "C" PRIMARY KEY CHECK (octet_length(tenant_id) BETWEEN 1 AND 256),
    in_flight BIGINT NOT NULL DEFAULT 0 CHECK (in_flight >= 0),
    initialized BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at_ms BIGINT NOT NULL DEFAULT (FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000)::BIGINT)
        CHECK (updated_at_ms >= 0)
);

CREATE TABLE outbox_dead_disposal (
    event_id TEXT COLLATE "C" PRIMARY KEY CHECK (octet_length(event_id) BETWEEN 1 AND 128),
    approval TEXT COLLATE "C" NOT NULL CHECK (octet_length(approval) BETWEEN 1 AND 128),
    receipt_event_id TEXT COLLATE "C" NOT NULL CHECK (octet_length(receipt_event_id) BETWEEN 1 AND 128),
    disposed_at_ms BIGINT NOT NULL DEFAULT (FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000)::BIGINT)
        CHECK (disposed_at_ms >= 0)
);
