//! PostgreSQL 持久 Outbox。
//!
//! 写侧复用 `natx-pgsql` ambient transaction；投递侧通过数据库 owner 租约与 fencing token
//! 约束 global/lane 权威，并以 `FOR UPDATE SKIP LOCKED` 按 `id` 升序领取。发布成功只确认精确前缀，
//! 取消或结果不确定保留至少一次重投语义。

#![forbid(unsafe_code)]

mod retention;
pub use retention::{RETENTION_COMMIT_UNCERTAIN_REASON, RETENTION_LOCK_CONTENTION_REASON};

use std::collections::BTreeMap;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::{Mutex, OnceLock};

use naoutbox_core::{
    DispatchReport, DurableOutboxAppend, DurableOutboxDispatch, DurableOutboxQuota,
    DurableOutboxRetention, DurableOutboxWakeup, OutboxArchive, OutboxEvent, OutboxPublishError,
    OutboxPublisher, OutboxRetentionPolicy, OutboxWriteContext, TENANT_QUOTA_EXCEEDED_REASON,
};
pub use naoutbox_core::{OutboxStoreError, RetentionRoundReport};
use sqlx::{PgConnection, PgPool, Postgres, Row as _, Transaction};
use tokio::sync::watch;

const OWNER_LEASE_MS: i64 = 30 * 1_000;
const PUBLISH_TIMEOUT_MS: u64 = 25 * 1_000;
const DEFAULT_OWNER_ROLE: &str = "dispatch-global";
const LANE_OWNER_ROLE: &str = "dispatch-lane";

const CREATE_SCHEMA_SQL: &str = r#"
CREATE TABLE IF NOT EXISTS outbox_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id TEXT COLLATE "C" NOT NULL CHECK (octet_length(event_id) BETWEEN 1 AND 128),
    aggregate_type TEXT COLLATE "C" NOT NULL CHECK (octet_length(aggregate_type) BETWEEN 1 AND 128),
    aggregate_id TEXT COLLATE "C" NOT NULL CHECK (octet_length(aggregate_id) BETWEEN 1 AND 190),
    event_type TEXT COLLATE "C" NOT NULL CHECK (octet_length(event_type) BETWEEN 1 AND 128),
    payload BYTEA NOT NULL,
    traceparent TEXT COLLATE "C" CHECK (octet_length(traceparent) BETWEEN 1 AND 64),
    tenant TEXT COLLATE "C" NOT NULL DEFAULT 'system' CHECK (octet_length(tenant) BETWEEN 1 AND 256),
    channel TEXT COLLATE "C" NOT NULL DEFAULT 'global' CHECK (octet_length(channel) BETWEEN 1 AND 64),
    dispatched BOOLEAN NOT NULL DEFAULT FALSE,
    attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    dead BOOLEAN NOT NULL DEFAULT FALSE,
    dead_at_ms BIGINT CHECK (dead_at_ms >= 0),
    created_at_ms BIGINT NOT NULL DEFAULT (FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000)::BIGINT)
        CHECK (created_at_ms >= 0),
    dispatched_at_ms BIGINT CHECK (dispatched_at_ms >= 0),
    CONSTRAINT outbox_event_event_id_key UNIQUE (event_id),
    CHECK (NOT dispatched OR NOT dead)
);
CREATE INDEX IF NOT EXISTS outbox_dispatchable_idx ON outbox_event (id)
    WHERE NOT dispatched AND NOT dead;
CREATE INDEX IF NOT EXISTS outbox_lane_dispatchable_idx ON outbox_event (channel, id)
    WHERE NOT dispatched AND NOT dead;
CREATE INDEX IF NOT EXISTS outbox_tenant_dispatchable_idx ON outbox_event (tenant, id)
    WHERE NOT dispatched AND NOT dead;
CREATE INDEX IF NOT EXISTS outbox_dead_idx ON outbox_event (id) WHERE dead;
CREATE INDEX IF NOT EXISTS outbox_retention_dispatched_idx ON outbox_event (dispatched_at_ms, id)
    WHERE dispatched AND NOT dead;
CREATE INDEX IF NOT EXISTS outbox_retention_dead_idx ON outbox_event (dead_at_ms, id) WHERE dead;

CREATE TABLE IF NOT EXISTS outbox_dispatch_owner (
    owner_role TEXT COLLATE "C" NOT NULL CHECK (octet_length(owner_role) BETWEEN 1 AND 32),
    lane TEXT COLLATE "C" NOT NULL CHECK (octet_length(lane) BETWEEN 1 AND 64),
    owner_id TEXT COLLATE "C" NOT NULL CHECK (octet_length(owner_id) BETWEEN 1 AND 64),
    fencing_token BIGINT NOT NULL CHECK (fencing_token > 0),
    lease_until_ms BIGINT NOT NULL CHECK (lease_until_ms >= 0),
    CONSTRAINT outbox_dispatch_owner_pkey PRIMARY KEY (owner_role, lane)
);
CREATE INDEX IF NOT EXISTS outbox_dispatch_owner_lease_idx
    ON outbox_dispatch_owner (lease_until_ms, owner_role, lane);

CREATE TABLE IF NOT EXISTS outbox_tenant_quota (
    tenant_id TEXT COLLATE "C" PRIMARY KEY CHECK (octet_length(tenant_id) BETWEEN 1 AND 256),
    in_flight BIGINT NOT NULL DEFAULT 0 CHECK (in_flight >= 0),
    initialized BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at_ms BIGINT NOT NULL DEFAULT (FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000)::BIGINT)
        CHECK (updated_at_ms >= 0)
);

CREATE TABLE IF NOT EXISTS outbox_dead_disposal (
    event_id TEXT COLLATE "C" PRIMARY KEY CHECK (octet_length(event_id) BETWEEN 1 AND 128),
    approval TEXT COLLATE "C" NOT NULL CHECK (octet_length(approval) BETWEEN 1 AND 128),
    receipt_event_id TEXT COLLATE "C" NOT NULL CHECK (octet_length(receipt_event_id) BETWEEN 1 AND 128),
    disposed_at_ms BIGINT NOT NULL DEFAULT (FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000)::BIGINT)
        CHECK (disposed_at_ms >= 0)
);
"#;

/// 未安装通道路由时使用的默认 lane。
pub const DEFAULT_CHANNEL: &str = "global";

static CHANNEL_ROUTES: OnceLock<BTreeMap<String, String>> = OnceLock::new();
static TENANT_QUOTAS: OnceLock<BTreeMap<String, u64>> = OnceLock::new();
static QUOTA_REJECTIONS: AtomicU64 = AtomicU64::new(0);
// 提交信号以 datasource 与 lane 共同定界，避免一个业务链的提交唤醒无关 dispatcher。
type CommitSignalRegistry = BTreeMap<(String, String), watch::Sender<u64>>;
static COMMIT_SIGNALS: OnceLock<Mutex<CommitSignalRegistry>> = OnceLock::new();

/// 业务作用：校验 lane 名可安全用于列值、owner 主键与低基数观测标签。
///
/// 参数说明：
/// - `channel`：待校验的 lane 名称。
///
/// 返回：长度 1..=64 且只含小写字母、数字、`_-.` 时为 `true`。
pub fn valid_channel_name(channel: &str) -> bool {
    !channel.is_empty()
        && channel.len() <= 64
        && channel.bytes().all(|byte| {
            byte.is_ascii_lowercase() || byte.is_ascii_digit() || matches!(byte, b'_' | b'-' | b'.')
        })
}

/// 业务作用：在首笔 append 前安装进程级冻结的 aggregate type 到 lane 路由。
///
/// 参数说明：
/// - `routes`：aggregate type 到规范 lane 名的完整冻结映射。
///
/// 返回：首次安装或同值重放成功；输入非法或与既有冻结值不同时返回错误。
pub fn install_channel_routes(routes: BTreeMap<String, String>) -> Result<(), OutboxStoreError> {
    for (aggregate_type, channel) in &routes {
        if aggregate_type.is_empty() || aggregate_type.len() > 128 || !valid_channel_name(channel) {
            return Err(OutboxStoreError::new(
                "channel routes require bounded aggregate types and canonical channel names",
            ));
        }
    }
    let installed = CHANNEL_ROUTES.get_or_init(|| routes.clone());
    if installed != &routes {
        return Err(OutboxStoreError::new(
            "channel routes are frozen for the process lifetime",
        ));
    }
    Ok(())
}

/// 业务作用：按冻结路由解析事件 lane，保证同一 aggregate type 的新事件归属稳定。
///
/// 参数说明：
/// - `aggregate_type`：待写事件的聚合根类型。
///
/// 返回：命中路由时返回配置 lane，否则返回 [`DEFAULT_CHANNEL`]。
pub fn channel_of(aggregate_type: &str) -> &'static str {
    CHANNEL_ROUTES
        .get()
        .and_then(|routes| routes.get(aggregate_type).map(String::as_str))
        .unwrap_or(DEFAULT_CHANNEL)
}

/// 业务作用：在首笔受信 append 前安装进程级冻结的租户在飞配额。
///
/// 参数说明：
/// - `quotas`：受信租户身份到正数在飞上限的映射；未列出租户不设限。
///
/// 返回：首次安装或同值重放成功；身份、上限非法或配置改变时返回错误。
pub fn install_outbox_tenant_quotas(quotas: BTreeMap<String, u64>) -> Result<(), OutboxStoreError> {
    for (tenant, cap) in &quotas {
        if OutboxWriteContext::new(tenant.clone()).is_err() || *cap == 0 || *cap > i64::MAX as u64 {
            return Err(OutboxStoreError::new(
                "tenant quotas require canonical tenant names and PostgreSQL BIGINT limits",
            ));
        }
    }
    let installed = TENANT_QUOTAS.get_or_init(|| quotas.clone());
    if installed != &quotas {
        return Err(OutboxStoreError::new(
            "tenant quotas are frozen for the process lifetime",
        ));
    }
    Ok(())
}

/// 业务作用：读取受信租户的冻结在飞上限。
///
/// 参数说明：
/// - `tenant`：受信租户身份。
///
/// 返回：列入冻结配置时返回正数上限，未列出时返回 `None`。
pub fn outbox_tenant_quota_of(tenant: &str) -> Option<u64> {
    TENANT_QUOTAS
        .get()
        .and_then(|quotas| quotas.get(tenant).copied())
}

/// 业务作用：读取当前进程因租户配额拒绝的 append 总数。
///
/// 参数说明: 无。
///
/// 返回：单调递增的低基数计数，不暴露租户标签。
pub fn outbox_quota_rejections_total() -> u64 {
    QUOTA_REJECTIONS.load(Ordering::Relaxed)
}

/// 业务作用：判断当前进程是否已经冻结租户配额，供 Ready 结构门禁决定是否校验账本。
///
/// 参数说明: 无。
///
/// 返回：至少配置一个租户上限时为真。
fn tenant_quotas_enabled() -> bool {
    TENANT_QUOTAS.get().is_some_and(|quotas| !quotas.is_empty())
}

/// 业务作用：在默认 PostgreSQL datasource 上校验 Outbox 通用事件表合同。
///
/// 参数说明: 无。
///
/// 返回：`outbox_event.tenant` 存在时成功；连接或结构缺失时返回脱敏错误。
pub async fn verify_outbox_event_schema() -> Result<(), OutboxStoreError> {
    verify_outbox_event_schema_for(natx_pgsql::DEFAULT_DATASOURCE).await
}

/// 业务作用：在指定 PostgreSQL datasource 上校验 Outbox 通用事件表合同。
///
/// 参数说明：`datasource` 是受管计划绑定的规范 datasource 名。
///
/// 返回：当前 schema 中存在租户归因列时成功；名称、连接或结构不满足时失败。
pub async fn verify_outbox_event_schema_for(
    datasource: impl AsRef<str>,
) -> Result<(), OutboxStoreError> {
    let datasource = natx_pgsql::DatasourceRef::new(datasource).map_err(map_err)?;
    let mut connection = natx_pgsql::conn_for(&datasource).await.map_err(map_err)?;
    verify_outbox_event_schema_on(connection.as_mut()).await
}

/// 业务作用：复用已取得的 PostgreSQL 会话检查事件表租户列，避免组合门禁重复占用连接池。
///
/// 参数说明：`connection` 是 Ready 阶段当前 datasource 的独占会话。
///
/// 返回：列存在时成功；缺列或查询失败时返回稳定错误。
async fn verify_outbox_event_schema_on(
    connection: &mut PgConnection,
) -> Result<(), OutboxStoreError> {
    let exists: bool = sqlx::query_scalar(
        "SELECT EXISTS (SELECT 1 FROM information_schema.columns \
         WHERE table_schema = current_schema() AND table_name = 'outbox_event' \
         AND column_name = 'tenant')",
    )
    .fetch_one(connection)
    .await
    .map_err(map_err)?;
    if !exists {
        return Err(OutboxStoreError::new(
            "outbox requires the outbox_event.tenant column",
        ));
    }
    Ok(())
}

/// 业务作用：在默认 PostgreSQL datasource 上校验租户配额账本与初始化状态。
///
/// 参数说明: 无。
///
/// 返回：未启用配额或账本完整时成功；结构或初始化缺失时失败。
pub async fn verify_outbox_tenant_quota_schema() -> Result<(), OutboxStoreError> {
    verify_outbox_tenant_quota_schema_for(natx_pgsql::DEFAULT_DATASOURCE).await
}

/// 业务作用：在指定 PostgreSQL datasource 上复验租户配额所需持久合同。
///
/// 参数说明：`datasource` 是受管 Outbox 计划绑定的规范 datasource 名。
///
/// 返回：未启用配额或事件表、账本及受限租户初始化状态齐备时成功；否则失败。
pub async fn verify_outbox_tenant_quota_schema_for(
    datasource: impl AsRef<str>,
) -> Result<(), OutboxStoreError> {
    if !tenant_quotas_enabled() {
        return Ok(());
    }
    let datasource = natx_pgsql::DatasourceRef::new(datasource).map_err(map_err)?;
    let mut connection = natx_pgsql::conn_for(&datasource).await.map_err(map_err)?;
    verify_outbox_event_schema_on(connection.as_mut()).await?;
    let has_ledger: bool = sqlx::query_scalar(
        "SELECT to_regclass(current_schema() || '.outbox_tenant_quota') IS NOT NULL",
    )
    .fetch_one(connection.as_mut())
    .await
    .map_err(map_err)?;
    if !has_ledger {
        return Err(OutboxStoreError::new(
            "outbox tenant quotas require the outbox_tenant_quota table",
        ));
    }
    if let Some(quotas) = TENANT_QUOTAS.get() {
        for tenant in quotas.keys() {
            let initialized: Option<bool> = sqlx::query_scalar(
                "SELECT initialized FROM outbox_tenant_quota WHERE tenant_id = $1",
            )
            .bind(tenant)
            .fetch_optional(connection.as_mut())
            .await
            .map_err(map_err)?;
            if initialized != Some(true) {
                return Err(OutboxStoreError::new(
                    "outbox tenant quota ledger for a capped tenant is not initialized",
                ));
            }
        }
    }
    Ok(())
}

/// PostgreSQL Outbox 句柄；全部写入、投递和治理操作固定到构造时选择的 datasource。
#[derive(Debug, Clone)]
pub struct PgOutbox {
    datasource: natx_pgsql::DatasourceRef,
}

impl Default for PgOutbox {
    /// 业务作用：创建绑定默认 PostgreSQL datasource 的轻量 Outbox 句柄。
    ///
    /// 参数说明: 无。
    ///
    /// 返回：与 [`PgOutbox::new`] 相同的句柄。
    fn default() -> Self {
        Self::new()
    }
}

#[derive(Debug, Clone)]
/// 业务作用：把 PostgreSQL 内部行身份与已校验的公开 Outbox 事件绑定供顺序投递。
struct PendingRow {
    id: i64,
    event: OutboxEvent,
}

/// 数据库持久 owner claim；token 是所有结果写与清理写的 fencing 条件。
struct OwnerClaim {
    pool: PgPool,
    role: &'static str,
    lane: String,
    owner_id: String,
    token: i64,
}

impl OwnerClaim {
    /// 业务作用：在继续发布下一条事件前延长当前 owner 租约，并复验 fencing token 未被接管。
    ///
    /// 参数说明：
    /// - `lease_ms`：从数据库当前时刻起延长的租约毫秒数。
    ///
    /// 返回：仍持权且续租成功时完成；租约过期、失权或数据库失败返回错误。
    async fn renew(&self, lease_ms: i64) -> Result<(), OutboxStoreError> {
        // 续租必须同时匹配 owner 身份、token 和未过期租约，旧实例不能让已经失效的权威重新生效。
        let renewed = sqlx::query(
            "UPDATE outbox_dispatch_owner SET \
             lease_until_ms = FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000)::BIGINT + $1 \
             WHERE owner_role = $2 AND lane = $3 AND owner_id = $4 AND fencing_token = $5 \
             AND lease_until_ms >= FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000)::BIGINT",
        )
        .bind(lease_ms)
        .bind(self.role)
        .bind(&self.lane)
        .bind(&self.owner_id)
        .bind(self.token)
        .execute(&self.pool)
        .await
        .map_err(map_err)?;
        if renewed.rows_affected() != 1 {
            return Err(OutboxStoreError::new("outbox dispatch ownership was lost"));
        }
        Ok(())
    }

    /// 业务作用：在完成正常轮次后提前释放 owner 租约，让下一轮无需等待到期。
    ///
    /// 参数说明: 无。
    ///
    /// 返回：仍持有相同 fencing token 时释放成功；失权或数据库失败返回错误。
    async fn release(self) -> Result<(), OutboxStoreError> {
        // 释放只作用于当前 token；已经被接管的旧实例不能缩短新 owner 的租约。
        let released = sqlx::query(
            "UPDATE outbox_dispatch_owner SET lease_until_ms = 0 \
             WHERE owner_role = $1 AND lane = $2 AND owner_id = $3 AND fencing_token = $4",
        )
        .bind(self.role)
        .bind(&self.lane)
        .bind(&self.owner_id)
        .bind(self.token)
        .execute(&self.pool)
        .await
        .map_err(map_err)?;
        if released.rows_affected() != 1 {
            return Err(OutboxStoreError::new("outbox dispatch ownership was lost"));
        }
        Ok(())
    }
}

impl PgOutbox {
    /// 业务作用：创建绑定默认 PostgreSQL datasource 的 Outbox 入口，不提前建立连接或取得 owner。
    ///
    /// 参数说明: 无。
    ///
    /// 返回：可用于事务写侧和独立投递侧的轻量句柄。
    pub fn new() -> Self {
        Self {
            datasource: natx_pgsql::DatasourceRef::default(),
        }
    }

    /// 业务作用：创建绑定命名 PostgreSQL datasource 的 Outbox 入口。
    ///
    /// 参数说明：
    /// - `datasource`：启动期已登记的稳定 datasource 名称。
    ///
    /// 返回：名称合法时返回固定绑定句柄；非法名称在网络 I/O 前失败。
    pub fn with_datasource(datasource: impl AsRef<str>) -> Result<Self, OutboxStoreError> {
        Ok(Self {
            datasource: natx_pgsql::DatasourceRef::new(datasource)
                .map_err(|_| OutboxStoreError::new("invalid outbox datasource name"))?,
        })
    }

    /// 业务作用：读取该 Outbox 全部持久操作绑定的 datasource 身份。
    ///
    /// 参数说明: 无。
    ///
    /// 返回：不可变且不含 endpoint 或凭据的 qualifier 引用。
    pub fn datasource_ref(&self) -> &natx_pgsql::DatasourceRef {
        &self.datasource
    }

    /// 业务作用：在写 SQL 前复验 ambient transaction 与句柄 datasource 完全一致。
    ///
    /// 参数说明: 无。
    ///
    /// 返回：同源事务存在时成功；事务缺失或跨 datasource 时返回稳定错误。
    fn require_ambient_datasource(&self) -> Result<(), OutboxStoreError> {
        match natx_pgsql::current_datasource() {
            Some(current) if current == self.datasource => Ok(()),
            Some(_) => Err(OutboxStoreError::new(
                "ambient transaction datasource mismatch",
            )),
            None => Err(OutboxStoreError::new("ambient transaction is required")),
        }
    }

    /// 业务作用：为显式自举在默认 datasource 创建当前 Outbox 全部表与 PostgreSQL 索引。
    ///
    /// 参数说明: 无。
    ///
    /// 返回：结构已存在或创建成功时完成；连接与 DDL 失败返回脱敏错误。
    pub async fn ensure_schema() -> Result<(), OutboxStoreError> {
        Self::ensure_schema_for(natx_pgsql::DEFAULT_DATASOURCE).await
    }

    /// 业务作用：为显式自举在命名 datasource 创建当前 Outbox 全部表与 PostgreSQL 索引。
    ///
    /// 参数说明：
    /// - `datasource`：启动期已登记的 PostgreSQL datasource 名称。
    ///
    /// 返回：结构已存在或创建成功时完成；名称、连接或 DDL 失败返回脱敏错误。
    pub async fn ensure_schema_for(datasource: impl AsRef<str>) -> Result<(), OutboxStoreError> {
        let datasource = natx_pgsql::DatasourceRef::new(datasource).map_err(map_err)?;
        let mut connection = natx_pgsql::conn_for(&datasource).await.map_err(map_err)?;
        Self::ensure_schema_on_connection(&mut connection).await
    }

    /// 业务作用：复用调用方已持有的 PostgreSQL 连接创建当前 Outbox 表和索引，使外层
    /// schema 互斥权覆盖整个结构操作。
    ///
    /// 参数说明：`connection` 是调用方已取得 schema 互斥权的连接。
    ///
    /// 返回：结构已存在或创建成功时完成；DDL 失败返回脱敏错误。
    pub async fn ensure_schema_on_connection(
        connection: &mut natx_pgsql::PgConn,
    ) -> Result<(), OutboxStoreError> {
        sqlx::raw_sql(CREATE_SCHEMA_SQL)
            .execute(connection.as_mut())
            .await
            .map_err(map_err)?;
        Ok(())
    }

    /// 业务作用：追加事件，并只在数据库明确提交后推进本进程唤醒代际。
    ///
    /// 参数说明：
    /// - `event`：携带稳定 `event_id` 的待发布事件。
    ///
    /// 返回：事务内写入并登记 after-commit，或事务外独立提交时成功；输入或数据库失败返回错误。
    pub async fn append(&self, event: &OutboxEvent) -> Result<(), OutboxStoreError> {
        validate_event(event)?;
        let transactional = natx_pgsql::in_transaction();
        if transactional {
            self.require_ambient_datasource()?;
        }
        let mut connection = natx_pgsql::conn_for(&self.datasource)
            .await
            .map_err(map_err)?;
        let inserted =
            Self::append_on_with_tenant(connection.as_mut(), event, naoutbox_core::SYSTEM_TENANT)
                .await?;
        drop(connection);
        if !inserted {
            return Ok(());
        }
        if transactional {
            // 唤醒只能跟随最外层事务的明确提交；登记失败必须向上传递，让调用方回滚本轮事件写入。
            register_commit_notification(
                self.datasource.as_str(),
                channel_of(&event.aggregate_type),
            )?;
        } else {
            notify_committed_append(self.datasource.as_str(), channel_of(&event.aggregate_type));
        }
        Ok(())
    }

    /// 业务作用：只在同源 PostgreSQL ambient transaction 内追加关键事件。
    ///
    /// 参数说明：
    /// - `event`：必须与当前业务事实原子提交的待发布事件。
    ///
    /// 返回：INSERT 和 after-commit 登记成功时完成；事务缺失、跨库或数据库失败返回错误。
    pub async fn append_transactional(&self, event: &OutboxEvent) -> Result<(), OutboxStoreError> {
        validate_event(event)?;
        self.require_ambient_datasource()?;
        let mut connection = natx_pgsql::mandatory_conn_for(&self.datasource)
            .await
            .map_err(map_err)?;
        let inserted =
            Self::append_on_with_tenant(connection.as_mut(), event, naoutbox_core::SYSTEM_TENANT)
                .await?;
        drop(connection);
        if inserted {
            // 事务提交前不开放本进程投递唤醒，避免 dispatcher 观察到尚未成为持久事实的事件。
            register_commit_notification(
                self.datasource.as_str(),
                channel_of(&event.aggregate_type),
            )?;
        }
        Ok(())
    }

    /// 业务作用：在同源事务内按受信租户上下文原子预留配额并追加事件。
    ///
    /// 参数说明：
    /// - `context`：已认证入口构造的租户上下文。
    /// - `event`：必须与业务事实原子提交的事件。
    ///
    /// 返回：预留、事件写入和 after-commit 登记全部完成时成功；配额或数据库失败返回错误。
    pub async fn append_transactional_with_context(
        &self,
        context: &OutboxWriteContext,
        event: &OutboxEvent,
    ) -> Result<(), OutboxStoreError> {
        validate_event(event)?;
        self.require_ambient_datasource()?;
        let mut connection = natx_pgsql::mandatory_conn_for(&self.datasource)
            .await
            .map_err(map_err)?;
        let mut quota_reserved = false;
        if let Some(cap) = outbox_tenant_quota_of(context.tenant()) {
            let cap = i64::try_from(cap).map_err(map_err)?;
            let already_exists: bool = sqlx::query_scalar(
                "SELECT EXISTS (SELECT 1 FROM outbox_event WHERE event_id = $1)",
            )
            .bind(&event.event_id)
            .fetch_one(connection.as_mut())
            .await
            .map_err(map_err)?;
            if already_exists {
                return Ok(());
            }
            // 账本行先创建并锁定，条件自增与事件 INSERT 共享事务，配额上限不会被并发穿透。
            sqlx::query(
                "INSERT INTO outbox_tenant_quota (tenant_id, in_flight) VALUES ($1, 0) \
                 ON CONFLICT (tenant_id) DO NOTHING",
            )
            .bind(context.tenant())
            .execute(connection.as_mut())
            .await
            .map_err(map_err)?;
            let reserved = sqlx::query(
                "UPDATE outbox_tenant_quota SET in_flight = in_flight + 1, \
                 updated_at_ms = FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000)::BIGINT \
                 WHERE tenant_id = $1 AND initialized AND in_flight < $2",
            )
            .bind(context.tenant())
            .bind(cap)
            .execute(connection.as_mut())
            .await
            .map_err(map_err)?;
            if reserved.rows_affected() == 0 {
                // 配额行锁等待期间另一事务可能已经提交同一 event_id；该请求没有新增事实，
                // 不应被当成配额拒绝，也不能再次占用额度。
                let already_exists: bool = sqlx::query_scalar(
                    "SELECT EXISTS (SELECT 1 FROM outbox_event WHERE event_id = $1)",
                )
                .bind(&event.event_id)
                .fetch_one(connection.as_mut())
                .await
                .map_err(map_err)?;
                if already_exists {
                    return Ok(());
                }
                let initialized: bool = sqlx::query_scalar(
                    "SELECT initialized FROM outbox_tenant_quota WHERE tenant_id = $1",
                )
                .bind(context.tenant())
                .fetch_one(connection.as_mut())
                .await
                .map_err(map_err)?;
                if !initialized {
                    return Err(OutboxStoreError::new(
                        "outbox tenant quota ledger is not initialized",
                    ));
                }
                QUOTA_REJECTIONS.fetch_add(1, Ordering::Relaxed);
                return Err(OutboxStoreError::new(TENANT_QUOTA_EXCEEDED_REASON));
            }
            quota_reserved = true;
        }
        let inserted =
            Self::append_on_with_tenant(connection.as_mut(), event, context.tenant()).await?;
        if quota_reserved && !inserted {
            // 重复 event_id 没有新增待投递事实，必须在同一账本行锁下撤销本轮预留，
            // 否则幂等重放会持续吞噬租户额度并最终拒绝真实新事件。
            sqlx::query(
                "UPDATE outbox_tenant_quota SET in_flight = in_flight - 1, \
                 updated_at_ms = FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000)::BIGINT \
                 WHERE tenant_id = $1 AND in_flight > 0",
            )
            .bind(context.tenant())
            .execute(connection.as_mut())
            .await
            .map_err(map_err)?;
        }
        drop(connection);
        if inserted {
            // 配额预留与事件写入必须先由业务事务共同提交，随后才能发布可合并的唤醒信号。
            register_commit_notification(
                self.datasource.as_str(),
                channel_of(&event.aggregate_type),
            )?;
        }
        Ok(())
    }

    /// 业务作用：在调用方连接内幂等写入完整事件，不改变事务提交所有权。
    ///
    /// 参数说明：
    /// - `connection`：ambient transaction 或独立提交路径持有的 PostgreSQL 连接。
    /// - `event`：已通过公共边界校验的事件。
    /// - `tenant`：受信写入上下文给出的租户；兼容入口固定传 `system`。
    ///
    /// 返回：目标 `event_id` 首次写入时为 `true`，已存在时为 `false`；其它约束与数据库失败返回错误。
    async fn append_on_with_tenant(
        connection: &mut PgConnection,
        event: &OutboxEvent,
        tenant: &str,
    ) -> Result<bool, OutboxStoreError> {
        let result = sqlx::query(
            "INSERT INTO outbox_event \
             (event_id, aggregate_type, aggregate_id, event_type, payload, traceparent, tenant, channel) \
             VALUES ($1, $2, $3, $4, $5, $6, $7, $8) \
             ON CONFLICT ON CONSTRAINT outbox_event_event_id_key DO NOTHING",
        )
        .bind(&event.event_id)
        .bind(&event.aggregate_type)
        .bind(&event.aggregate_id)
        .bind(&event.event_type)
        .bind(&event.payload)
        .bind(&event.traceparent)
        .bind(tenant)
        .bind(channel_of(&event.aggregate_type))
        .execute(connection)
        .await
        .map_err(map_err)?;
        Ok(result.rows_affected() == 1)
    }

    /// 业务作用：读取全部可投递且非死信事件数量。
    ///
    /// 参数说明：无。
    ///
    /// 返回：基于 partial index 的非负积压数；数据库失败返回错误。
    pub async fn pending_count(&self) -> Result<u64, OutboxStoreError> {
        let mut connection = natx_pgsql::conn_for(&self.datasource)
            .await
            .map_err(map_err)?;
        let count: i64 = sqlx::query_scalar(
            "SELECT COUNT(*) FROM outbox_event WHERE NOT dispatched AND NOT dead",
        )
        .fetch_one(connection.as_mut())
        .await
        .map_err(map_err)?;
        Ok(count.max(0) as u64)
    }

    /// 业务作用：读取死信集合数量，供告警和人工恢复决策使用。
    ///
    /// 参数说明：无。
    ///
    /// 返回：基于 dead partial index 的非负计数；数据库失败返回错误。
    pub async fn dead_count(&self) -> Result<u64, OutboxStoreError> {
        let mut connection = natx_pgsql::conn_for(&self.datasource)
            .await
            .map_err(map_err)?;
        let count: i64 = sqlx::query_scalar("SELECT COUNT(*) FROM outbox_event WHERE dead")
            .fetch_one(connection.as_mut())
            .await
            .map_err(map_err)?;
        Ok(count.max(0) as u64)
    }

    /// 业务作用：读取单个 lane 的可投递且非死信事件数量。
    ///
    /// 参数说明：
    /// - `channel`：规范 lane 名称。
    ///
    /// 返回：该 lane 的非负积压数；名称非法或数据库失败返回错误。
    pub async fn pending_count_channel(&self, channel: &str) -> Result<u64, OutboxStoreError> {
        if !valid_channel_name(channel) {
            return Err(OutboxStoreError::new("invalid outbox channel name"));
        }
        let mut connection = natx_pgsql::conn_for(&self.datasource)
            .await
            .map_err(map_err)?;
        let count: i64 = sqlx::query_scalar(
            "SELECT COUNT(*) FROM outbox_event \
             WHERE channel = $1 AND NOT dispatched AND NOT dead",
        )
        .bind(channel)
        .fetch_one(connection.as_mut())
        .await
        .map_err(map_err)?;
        Ok(count.max(0) as u64)
    }

    /// 业务作用：读取受信租户精确在飞账本值。
    ///
    /// 参数说明：
    /// - `tenant`：受鉴权管理入口给出的租户身份。
    ///
    /// 返回：账本不存在时为零；身份非法或数据库失败返回错误。
    pub async fn outbox_tenant_quota_usage(&self, tenant: &str) -> Result<u64, OutboxStoreError> {
        validate_tenant(tenant)?;
        let mut connection = natx_pgsql::conn_for(&self.datasource)
            .await
            .map_err(map_err)?;
        let count: Option<i64> =
            sqlx::query_scalar("SELECT in_flight FROM outbox_tenant_quota WHERE tenant_id = $1")
                .bind(tenant)
                .fetch_optional(connection.as_mut())
                .await
                .map_err(map_err)?;
        Ok(count.unwrap_or(0).max(0) as u64)
    }

    /// 业务作用：在同源事务内先锁租户账本，再按持久待投递事实重算在飞数并开放配额。
    ///
    /// 参数说明：
    /// - `tenant`：受鉴权管理入口给出的租户身份。
    ///
    /// 返回：对账后的在飞数；事务缺失、跨库、身份非法或数据库失败返回错误。
    pub async fn reconcile_outbox_tenant_quota(
        &self,
        tenant: &str,
    ) -> Result<u64, OutboxStoreError> {
        validate_tenant(tenant)?;
        self.require_ambient_datasource()?;
        let mut connection = natx_pgsql::mandatory_conn_for(&self.datasource)
            .await
            .map_err(map_err)?;
        sqlx::query(
            "INSERT INTO outbox_tenant_quota (tenant_id, in_flight) VALUES ($1, 0) \
             ON CONFLICT (tenant_id) DO NOTHING",
        )
        .bind(tenant)
        .execute(connection.as_mut())
        .await
        .map_err(map_err)?;
        let _: i64 = sqlx::query_scalar(
            "SELECT in_flight FROM outbox_tenant_quota WHERE tenant_id = $1 FOR UPDATE",
        )
        .bind(tenant)
        .fetch_one(connection.as_mut())
        .await
        .map_err(map_err)?;
        let actual: i64 = sqlx::query_scalar(
            "SELECT COUNT(*) FROM outbox_event \
             WHERE tenant = $1 AND NOT dispatched AND NOT dead",
        )
        .bind(tenant)
        .fetch_one(connection.as_mut())
        .await
        .map_err(map_err)?;
        sqlx::query(
            "UPDATE outbox_tenant_quota SET in_flight = $1, initialized = TRUE, \
             updated_at_ms = FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000)::BIGINT \
             WHERE tenant_id = $2",
        )
        .bind(actual)
        .bind(tenant)
        .execute(connection.as_mut())
        .await
        .map_err(map_err)?;
        Ok(actual.max(0) as u64)
    }

    /// 业务作用：在数据库 owner fencing 下按 `id` 升序投递一个 global 批次。
    ///
    /// 参数说明：
    /// - `publisher`：至少一次发布端。
    /// - `limit`：本轮最多领取的事件数。
    ///
    /// 返回：未取得 owner 时为空报告；否则只确认成功前缀并返回报告；存储失败返回错误。
    pub async fn dispatch_batch<P>(
        &self,
        publisher: &P,
        limit: u32,
    ) -> Result<DispatchReport, OutboxStoreError>
    where
        P: OutboxPublisher + ?Sized,
    {
        self.dispatch_inner(publisher, None, limit, None).await
    }

    /// 业务作用：投递 global 批次，并只对确定性首失败累计死信预算。
    ///
    /// 参数说明：
    /// - `publisher`：至少一次发布端。
    /// - `limit`：本轮最多领取的事件数。
    /// - `max_attempts`：确定性失败进入死信集合前的轮次上限。
    ///
    /// 返回：本轮发布报告；阈值非法或存储失败返回错误。
    pub async fn dispatch_batch_with_dlt<P>(
        &self,
        publisher: &P,
        limit: u32,
        max_attempts: u32,
    ) -> Result<DispatchReport, OutboxStoreError>
    where
        P: OutboxPublisher + ?Sized,
    {
        if max_attempts == 0 {
            return Err(OutboxStoreError::new(
                "max_attempts must be greater than zero",
            ));
        }
        self.dispatch_inner(publisher, None, limit, Some(max_attempts))
            .await
    }

    /// 业务作用：在独立 lane owner fencing 下按 `id` 升序投递一个 lane 批次。
    ///
    /// 参数说明：
    /// - `publisher`：至少一次发布端。
    /// - `channel`：冻结路由生成的 lane 名称。
    /// - `limit`：本轮最多领取的事件数。
    ///
    /// 返回：未取得 owner 时为空报告；否则返回 lane 报告；输入或数据库失败返回错误。
    pub async fn dispatch_batch_channel<P>(
        &self,
        publisher: &P,
        channel: &str,
        limit: u32,
    ) -> Result<DispatchReport, OutboxStoreError>
    where
        P: OutboxPublisher + ?Sized,
    {
        if !valid_channel_name(channel) {
            return Err(OutboxStoreError::new("invalid outbox channel name"));
        }
        self.dispatch_inner(publisher, Some(channel), limit, None)
            .await
    }

    /// 业务作用：投递单 lane，并只对确定性首失败累计该 lane 的死信预算。
    ///
    /// 参数说明：
    /// - `publisher`：至少一次发布端。
    /// - `channel`：冻结路由生成的 lane 名称。
    /// - `limit`：本轮最多领取的事件数。
    /// - `max_attempts`：确定性失败进入死信集合前的轮次上限。
    ///
    /// 返回：本轮 lane 报告；输入非法或存储失败返回错误。
    pub async fn dispatch_batch_channel_with_dlt<P>(
        &self,
        publisher: &P,
        channel: &str,
        limit: u32,
        max_attempts: u32,
    ) -> Result<DispatchReport, OutboxStoreError>
    where
        P: OutboxPublisher + ?Sized,
    {
        if max_attempts == 0 {
            return Err(OutboxStoreError::new(
                "max_attempts must be greater than zero",
            ));
        }
        if !valid_channel_name(channel) {
            return Err(OutboxStoreError::new("invalid outbox channel name"));
        }
        self.dispatch_inner(publisher, Some(channel), limit, Some(max_attempts))
            .await
    }

    /// 业务作用：统一 global/lane owner 竞争、候选领取、成功前缀确认与死信裁决。
    ///
    /// 参数说明：
    /// - `publisher`：至少一次发布端。
    /// - `channel`：`None` 表示 global；有值表示单 lane。
    /// - `limit`：本轮最多领取的事件数。
    /// - `max_attempts`：有值时启用确定性死信预算。
    ///
    /// 返回：未取得 owner 时为空报告；正常轮次释放 owner 后返回报告；失权或数据库失败返回错误。
    async fn dispatch_inner<P>(
        &self,
        publisher: &P,
        channel: Option<&str>,
        limit: u32,
        max_attempts: Option<u32>,
    ) -> Result<DispatchReport, OutboxStoreError>
    where
        P: OutboxPublisher + ?Sized,
    {
        if natx_pgsql::in_transaction() {
            return Err(OutboxStoreError::new(
                "dispatcher cannot run inside an ambient transaction",
            ));
        }
        let role = if channel.is_some() {
            LANE_OWNER_ROLE
        } else {
            DEFAULT_OWNER_ROLE
        };
        let lane = channel.unwrap_or(DEFAULT_CHANNEL);
        // 只有数据库原子授予 role/lane 权威后才允许读取候选，未取得 owner 的实例不能接触投递后缀。
        let Some(claim) = self.try_claim_owner(role, lane, OWNER_LEASE_MS).await? else {
            return Ok(empty_report());
        };
        let pending = self.poll_pending(&claim, channel, limit).await?;
        let events: Vec<OutboxEvent> = pending.iter().map(|row| row.event.clone()).collect();
        let report = dispatch_in_order_fenced(&claim, &events, publisher).await?;
        if report.published > 0 {
            self.mark_dispatched_exact(&claim, &pending[..report.published])
                .await?;
        }
        if let Some(max_attempts) = max_attempts {
            if report
                .first_error
                .as_ref()
                .is_some_and(|error| !error.is_transient())
                && report.published < pending.len()
            {
                self.record_failed_attempt(&claim, &pending[report.published], max_attempts)
                    .await?;
            }
        }
        // 正常轮次的全部数据库结果已经确认后再提前释放；中途取消或失权则保留租约到期门禁。
        claim.release().await?;
        Ok(report)
    }

    /// 业务作用：原子取得或接管一个 role/lane owner，并递增 fencing token。
    ///
    /// 参数说明：
    /// - `role`：global、lane 或 retention 等封闭执行角色。
    /// - `lane`：角色内的稳定 shard 身份。
    /// - `lease_ms`：本轮 owner 租约时长。
    ///
    /// 返回：首次创建或过期接管返回 claim；未过期 owner 存在时返回 `None`；数据库失败返回错误。
    async fn try_claim_owner(
        &self,
        role: &'static str,
        lane: &str,
        lease_ms: i64,
    ) -> Result<Option<OwnerClaim>, OutboxStoreError> {
        let pool = natx_pgsql::pool_for_datasource(self.datasource.as_str()).map_err(map_err)?;
        let owner_id = uuid::Uuid::new_v4().to_string();
        // 接管条件、owner 身份与 fencing token 在单条语句中改变，旧实例无法凭过期 token 继续写结果。
        let token: Option<i64> = sqlx::query_scalar(
            "INSERT INTO outbox_dispatch_owner \
             (owner_role, lane, owner_id, fencing_token, lease_until_ms) \
             VALUES ($1, $2, $3, 1, FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000)::BIGINT + $4) \
             ON CONFLICT (owner_role, lane) DO UPDATE SET owner_id = EXCLUDED.owner_id, \
             fencing_token = outbox_dispatch_owner.fencing_token + 1, \
             lease_until_ms = FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000)::BIGINT + $4 \
             WHERE outbox_dispatch_owner.lease_until_ms < \
                 FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000)::BIGINT \
             RETURNING fencing_token",
        )
        .bind(role)
        .bind(lane)
        .bind(&owner_id)
        .bind(lease_ms)
        .fetch_optional(&pool)
        .await
        .map_err(map_err)?;
        Ok(token.map(|token| OwnerClaim {
            pool,
            role,
            lane: lane.to_string(),
            owner_id,
            token,
        }))
    }

    /// 业务作用：在 owner 行锁与 fencing 复验后，以 `SKIP LOCKED` 领取稳定 id 前缀。
    ///
    /// 参数说明：
    /// - `claim`：本轮数据库 owner 权威。
    /// - `channel`：`None` 为 global，有值为单 lane。
    /// - `limit`：最多领取行数。
    ///
    /// 返回：短事务明确提交后返回候选；失权、提交不确定或数据库失败返回错误且不发布。
    async fn poll_pending(
        &self,
        claim: &OwnerClaim,
        channel: Option<&str>,
        limit: u32,
    ) -> Result<Vec<PendingRow>, OutboxStoreError> {
        let mut transaction = claim.pool.begin().await.map_err(map_err)?;
        // 候选读取前先锁定并复验 owner 行，失权实例不能领取新的外部副作用工作。
        ensure_owner(&mut transaction, claim).await?;
        let rows = match channel {
            Some(channel) => {
                sqlx::query(
                    "SELECT id, event_id, aggregate_type, aggregate_id, event_type, payload, \
                 traceparent, tenant FROM outbox_event \
                 WHERE channel = $1 AND NOT dispatched AND NOT dead ORDER BY id ASC \
                 LIMIT $2 FOR UPDATE SKIP LOCKED",
                )
                .bind(channel)
                .bind(i64::from(limit))
                .fetch_all(&mut *transaction)
                .await
            }
            None => {
                sqlx::query(
                    "SELECT id, event_id, aggregate_type, aggregate_id, event_type, payload, \
                 traceparent, tenant FROM outbox_event \
                 WHERE NOT dispatched AND NOT dead ORDER BY id ASC \
                 LIMIT $1 FOR UPDATE SKIP LOCKED",
                )
                .bind(i64::from(limit))
                .fetch_all(&mut *transaction)
                .await
            }
        }
        .map_err(map_err)?;
        commit_transaction(transaction).await?;
        rows.into_iter().map(parse_pending).collect()
    }

    /// 业务作用：在同一 fenced 事务中标记成功前缀并释放对应租户在飞名额。
    ///
    /// 参数说明：
    /// - `claim`：本轮数据库 owner 权威。
    /// - `rows`：已按顺序得到下游明确确认的精确前缀。
    ///
    /// 返回：全部行仍匹配待投递事实且提交明确时成功；失权、漂移或数据库失败返回错误。
    async fn mark_dispatched_exact(
        &self,
        claim: &OwnerClaim,
        rows: &[PendingRow],
    ) -> Result<(), OutboxStoreError> {
        let mut transaction = claim.pool.begin().await.map_err(map_err)?;
        // 外部发布成功不等于仍有数据库写权；先复验 fencing，避免旧 owner 确认新 owner 的事件。
        ensure_owner(&mut transaction, claim).await?;
        for row in rows {
            let tenant: Option<String> = sqlx::query_scalar(
                "UPDATE outbox_event SET dispatched = TRUE, \
                 dispatched_at_ms = FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000)::BIGINT \
                 WHERE id = $1 AND event_id = $2 AND NOT dispatched AND NOT dead RETURNING tenant",
            )
            .bind(row.id)
            .bind(&row.event.event_id)
            .fetch_optional(&mut *transaction)
            .await
            .map_err(map_err)?;
            let Some(tenant) = tenant else {
                return Err(OutboxStoreError::new(
                    "outbox success prefix no longer matches pending facts",
                ));
            };
            release_quota(&mut transaction, &tenant).await?;
        }
        commit_transaction(transaction).await
    }

    /// 业务作用：在 owner fencing 下累计确定性首失败，并在阈值到达时原子释放租户名额。
    ///
    /// 参数说明：
    /// - `claim`：本轮数据库 owner 权威。
    /// - `row`：首个未确认事件。
    /// - `max_attempts`：进入死信集合前的确定性失败轮次上限。
    ///
    /// 返回：失败计数与可能的死信转换明确提交时成功；失权或数据库失败返回错误。
    async fn record_failed_attempt(
        &self,
        claim: &OwnerClaim,
        row: &PendingRow,
        max_attempts: u32,
    ) -> Result<(), OutboxStoreError> {
        let mut transaction = claim.pool.begin().await.map_err(map_err)?;
        // 失败预算会改变死信与租户配额，必须在同一事务内先确认当前 owner 权威。
        ensure_owner(&mut transaction, claim).await?;
        let result = sqlx::query(
            "UPDATE outbox_event SET attempts = attempts + 1, \
             dead = attempts + 1 >= $1, \
             dead_at_ms = CASE WHEN attempts + 1 >= $1 THEN \
                 FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000)::BIGINT ELSE dead_at_ms END \
             WHERE id = $2 AND event_id = $3 AND NOT dispatched AND NOT dead \
             RETURNING tenant, dead",
        )
        .bind(i64::from(max_attempts))
        .bind(row.id)
        .bind(&row.event.event_id)
        .fetch_optional(&mut *transaction)
        .await
        .map_err(map_err)?;
        let Some(result) = result else {
            return Err(OutboxStoreError::new(
                "outbox failed event no longer matches pending facts",
            ));
        };
        let tenant: String = result.try_get("tenant").map_err(map_err)?;
        let dead: bool = result.try_get("dead").map_err(map_err)?;
        if dead {
            release_quota(&mut transaction, &tenant).await?;
        }
        commit_transaction(transaction).await
    }

    /// 业务作用：订阅当前进程 PostgreSQL Outbox 的已确认提交代际。
    ///
    /// 参数说明：`channel` 指定 lane 时只订阅该 lane；未指定时订阅当前 datasource 的全局代际。
    ///
    /// 返回：初值为当前代际的 watch 接收端；调用方仍须保留数据库轮询。
    pub fn subscribe_committed_appends(&self, channel: Option<&str>) -> watch::Receiver<u64> {
        commit_signal(self.datasource.as_str(), channel.unwrap_or("*")).subscribe()
    }
}

/// 业务作用：在 owner 行锁下复验 role、lane、owner、token 与未过期租约。
///
/// 参数说明：
/// - `transaction`：即将写结果或领取候选的短 PostgreSQL 事务。
/// - `claim`：调用方持有的数据库 owner 权威。
///
/// 返回：权威仍有效时成功；失权时在任何结果写前拒绝。
async fn ensure_owner(
    transaction: &mut Transaction<'_, Postgres>,
    claim: &OwnerClaim,
) -> Result<(), OutboxStoreError> {
    // owner 行锁把权威复验与后续候选/结果写串在同一事务中，接管者必须等待该事务结束。
    let token: Option<i64> = sqlx::query_scalar(
        "SELECT fencing_token FROM outbox_dispatch_owner \
         WHERE owner_role = $1 AND lane = $2 AND owner_id = $3 AND fencing_token = $4 \
         AND lease_until_ms >= FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000)::BIGINT \
         FOR UPDATE",
    )
    .bind(claim.role)
    .bind(&claim.lane)
    .bind(&claim.owner_id)
    .bind(claim.token)
    .fetch_optional(&mut **transaction)
    .await
    .map_err(map_err)?;
    if token.is_none() {
        return Err(OutboxStoreError::new("outbox dispatch ownership was lost"));
    }
    Ok(())
}

/// 业务作用：在事件离开可投递集合的同一事务内释放已有租户账本名额。
///
/// 参数说明：
/// - `transaction`：持有事件状态变更的 PostgreSQL 事务。
/// - `tenant`：事件持久列中的受信租户归因。
///
/// 返回：账本不存在或幂等释放时成功；数据库失败返回错误并回滚事件状态变化。
async fn release_quota(
    transaction: &mut Transaction<'_, Postgres>,
    tenant: &str,
) -> Result<(), OutboxStoreError> {
    sqlx::query(
        "UPDATE outbox_tenant_quota SET in_flight = in_flight - 1, \
         updated_at_ms = FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000)::BIGINT \
         WHERE tenant_id = $1 AND in_flight > 0",
    )
    .bind(tenant)
    .execute(&mut **transaction)
    .await
    .map_err(map_err)?;
    Ok(())
}

/// 业务作用：把 PostgreSQL 行解析为后端中立事件并保留数据库主键。
///
/// 参数说明：
/// - `row`：按稳定 `id` 查询得到的待投递行。
///
/// 返回：字段类型与 schema 一致时返回候选；漂移或损坏返回脱敏错误。
fn parse_pending(row: sqlx::postgres::PgRow) -> Result<PendingRow, OutboxStoreError> {
    Ok(PendingRow {
        id: row.try_get("id").map_err(map_err)?,
        event: OutboxEvent {
            event_id: row.try_get("event_id").map_err(map_err)?,
            aggregate_type: row.try_get("aggregate_type").map_err(map_err)?,
            aggregate_id: row.try_get("aggregate_id").map_err(map_err)?,
            event_type: row.try_get("event_type").map_err(map_err)?,
            payload: row.try_get("payload").map_err(map_err)?,
            traceparent: row.try_get("traceparent").map_err(map_err)?,
            tenant: row.try_get("tenant").map_err(map_err)?,
        },
    })
}

/// 业务作用：提交短控制事务，并把连接级应答中断单独归类为提交结果不确定。
///
/// 参数说明：
/// - `transaction`：已经完成全部受 fencing 保护写入的 PostgreSQL 事务。
///
/// 返回：数据库明确确认提交时成功；拒绝、结果不确定或基础设施失败返回稳定错误。
async fn commit_transaction(
    transaction: Transaction<'_, Postgres>,
) -> Result<(), OutboxStoreError> {
    transaction.commit().await.map_err(map_commit_err)
}

/// 业务作用：校验公开事件字段能按 MySQL/PostgreSQL 公共字节边界无损持久化。
///
/// 参数说明：
/// - `event`：待进入持久 Outbox 的事件。
///
/// 返回：身份、路由字段与 trace context 合法时成功；否则在数据库 I/O 前返回脱敏错误。
fn validate_event(event: &OutboxEvent) -> Result<(), OutboxStoreError> {
    for value in [
        (&event.event_id, 128_usize),
        (&event.aggregate_type, 128),
        (&event.aggregate_id, 190),
        (&event.event_type, 128),
    ] {
        if value.0.is_empty() || value.0.len() > value.1 || value.0.contains('\0') {
            return Err(OutboxStoreError::new("invalid outbox event identity"));
        }
    }
    if event
        .traceparent
        .as_ref()
        .is_some_and(|value| value.is_empty() || value.len() > 64 || value.contains('\0'))
    {
        return Err(OutboxStoreError::new("invalid outbox trace context"));
    }
    Ok(())
}

/// 业务作用：校验租户身份符合受信写入上下文的公共边界。
///
/// 参数说明：
/// - `tenant`：待查询或对账的受信租户身份。
///
/// 返回：身份合法时成功；否则在数据库 I/O 前返回脱敏错误。
fn validate_tenant(tenant: &str) -> Result<(), OutboxStoreError> {
    OutboxWriteContext::new(tenant.to_string())
        .map(|_| ())
        .map_err(|_| OutboxStoreError::new("invalid outbox tenant"))
}

/// 业务作用：构造未取得 owner 时的稳定空投递报告。
///
/// 参数说明: 无。
///
/// 返回：published、total 均为零且无发布错误的报告。
fn empty_report() -> DispatchReport {
    DispatchReport {
        published: 0,
        total: 0,
        first_error: None,
    }
}

/// 业务作用：在每条发布前续租并限定单条等待时间，失权后不再推进批次后缀。
///
/// 参数说明：
/// - `claim`：本轮 global 或 lane owner 权威。
/// - `events`：按稳定 `id` 升序取得的候选事件。
/// - `publisher`：至少一次发布端。
///
/// 返回：成功前缀与首个发布失败；续租或数据库失败返回错误且未确认行保留重投。
async fn dispatch_in_order_fenced<P>(
    claim: &OwnerClaim,
    events: &[OutboxEvent],
    publisher: &P,
) -> Result<DispatchReport, OutboxStoreError>
where
    P: OutboxPublisher + ?Sized,
{
    let mut published = 0;
    let mut first_error = None;
    for event in events {
        // 发布是不可回滚的外部副作用；每条发送前先确认权威仍有效，避免租约到期后的旧实例继续推进后缀。
        claim.renew(OWNER_LEASE_MS).await?;
        match tokio::time::timeout(
            std::time::Duration::from_millis(PUBLISH_TIMEOUT_MS),
            publisher.publish(event),
        )
        .await
        {
            Ok(Ok(())) => published += 1,
            Ok(Err(error)) => {
                first_error = Some(error);
                break;
            }
            Err(_) => {
                first_error = Some(OutboxPublishError::transient(
                    "outbox publish deadline exceeded",
                ));
                break;
            }
        }
    }
    Ok(DispatchReport {
        published,
        total: events.len(),
        first_error,
    })
}

/// 业务作用：取得 PostgreSQL Outbox 指定 datasource 与 lane 的提交代际发布端。
///
/// 参数说明：
/// - `datasource`：写侧和 dispatcher 共同使用的 datasource 身份。
/// - `channel`：事件所属 lane，`*` 表示该 datasource 的全局订阅。
///
/// 返回：惰性创建且进程内按精确键稳定复用的 watch sender。
fn commit_signal(datasource: &str, channel: &str) -> watch::Sender<u64> {
    let signals = COMMIT_SIGNALS.get_or_init(|| Mutex::new(BTreeMap::new()));
    let mut signals = signals
        .lock()
        .unwrap_or_else(std::sync::PoisonError::into_inner);
    signals
        .entry((datasource.to_owned(), channel.to_owned()))
        .or_insert_with(|| watch::channel(0).0)
        .clone()
}

/// 业务作用：在数据库提交已经明确确认后推进精确 lane 与 datasource 全局唤醒代际。
///
/// 参数说明：
/// - `datasource`：事件实际落库的 datasource 身份。
/// - `channel`：事件持久化时解析出的 lane。
///
/// 返回：无；通知可被合并，持久待投递集合仍以数据库为准。
fn notify_committed_append(datasource: &str, channel: &str) {
    commit_signal(datasource, channel).send_modify(|generation| {
        *generation = generation.wrapping_add(1);
    });
    if channel != "*" {
        commit_signal(datasource, "*").send_modify(|generation| {
            *generation = generation.wrapping_add(1);
        });
    }
}

/// 业务作用：把唤醒登记到最外层 PostgreSQL ambient transaction 的明确提交之后。
///
/// 参数说明：
/// - `datasource`：事件实际写入的 datasource 身份。
/// - `channel`：事件持久化时解析出的 lane。
///
/// 返回：登记成功时完成；事务上下文丢失时返回错误并要求调用方回滚事件写入。
fn register_commit_notification(datasource: &str, channel: &str) -> Result<(), OutboxStoreError> {
    let datasource = datasource.to_owned();
    let channel = channel.to_owned();
    natx_pgsql::after_commit(move || async move {
        notify_committed_append(&datasource, &channel);
    })
    .map_err(map_err)
}

/// 业务作用：把 PostgreSQL COMMIT 错误分类为明确拒绝、应答不确定或基础设施失败。
///
/// 参数说明：
/// - `error`：SQLx 提交阶段返回的错误。
///
/// 返回：不含 SQL、endpoint 或事件内容的稳定错误。
fn map_commit_err(error: sqlx::Error) -> OutboxStoreError {
    match error {
        sqlx::Error::Database(_) => OutboxStoreError::new("outbox database rejected commit"),
        sqlx::Error::Io(_)
        | sqlx::Error::Tls(_)
        | sqlx::Error::Protocol(_)
        | sqlx::Error::WorkerCrashed => {
            OutboxStoreError::new("outbox database commit acknowledgement is uncertain")
        }
        _ => OutboxStoreError::new("outbox transaction commit infrastructure failed"),
    }
}

/// 业务作用：把底层连接、编码与数据库错误收敛为脱敏 Outbox 错误。
///
/// 参数说明：
/// - `_error`：仅触发分类、不进入公开文本的底层错误。
///
/// 返回：固定数据库错误分类。
pub(crate) fn map_err<E>(_error: E) -> OutboxStoreError {
    OutboxStoreError::new("database error")
}

#[async_trait::async_trait]
impl DurableOutboxAppend for PgOutbox {
    /// 业务作用：通过后端中立合同追加 PostgreSQL Outbox 事件。
    ///
    /// 参数说明：
    /// - `event`：携带稳定身份的待发布事件。
    ///
    /// 返回：写入与提交后唤醒登记完成时成功；输入或数据库失败返回错误。
    async fn append(&self, event: &OutboxEvent) -> Result<(), OutboxStoreError> {
        PgOutbox::append(self, event).await
    }

    /// 业务作用：通过后端中立合同在同源 PostgreSQL 事务内追加关键事件。
    ///
    /// 参数说明：
    /// - `event`：必须与业务事实同提交的待发布事件。
    ///
    /// 返回：写入与 after-commit 登记完成时成功；事务或数据库失败返回错误。
    async fn append_transactional(&self, event: &OutboxEvent) -> Result<(), OutboxStoreError> {
        PgOutbox::append_transactional(self, event).await
    }

    /// 业务作用：通过后端中立合同执行租户配额预留与事务内事件追加。
    ///
    /// 参数说明：
    /// - `context`：受信租户写入上下文。
    /// - `event`：必须与业务事实同提交的待发布事件。
    ///
    /// 返回：配额与事件事实同提交时成功；拒绝或数据库失败返回错误。
    async fn append_transactional_with_context(
        &self,
        context: &OutboxWriteContext,
        event: &OutboxEvent,
    ) -> Result<(), OutboxStoreError> {
        PgOutbox::append_transactional_with_context(self, context, event).await
    }
}

#[async_trait::async_trait]
impl DurableOutboxDispatch for PgOutbox {
    /// 业务作用：从本数据源已提交事件计算指定合同的最老排队时间。
    ///
    /// 参数说明：`event_type` 是待观测的固定事件合同名。
    ///
    /// 返回：非负毫秒数；无待确认事件时为零，数据库失败时返回错误。
    async fn oldest_pending_age_ms(&self, event_type: &str) -> Result<u64, OutboxStoreError> {
        let mut connection = natx_pgsql::conn_for(&self.datasource)
            .await
            .map_err(map_err)?;
        let age: i64 = sqlx::query_scalar("SELECT COALESCE(GREATEST(FLOOR(EXTRACT(EPOCH FROM clock_timestamp()) * 1000)::BIGINT - MIN(created_at_ms), 0), 0) FROM outbox_event WHERE NOT dispatched AND NOT dead AND event_type = $1")
            .bind(event_type).fetch_one(connection.as_mut()).await.map_err(map_err)?;
        Ok(age.max(0) as u64)
    }

    /// 业务作用：通过后端中立合同读取 PostgreSQL 可投递积压。
    ///
    /// 参数说明: 无。
    ///
    /// 返回：非负积压数；数据库失败返回错误。
    async fn pending_count(&self) -> Result<u64, OutboxStoreError> {
        PgOutbox::pending_count(self).await
    }

    /// 业务作用：通过后端中立合同读取 PostgreSQL 死信数量。
    ///
    /// 参数说明: 无。
    ///
    /// 返回：非负死信数；数据库失败返回错误。
    async fn dead_count(&self) -> Result<u64, OutboxStoreError> {
        PgOutbox::dead_count(self).await
    }

    /// 业务作用：通过后端中立合同投递 PostgreSQL global 批次并确认成功前缀。
    ///
    /// 参数说明：
    /// - `publisher`：至少一次发布端。
    /// - `limit`：本轮最多领取的事件数。
    ///
    /// 返回：本轮发布报告；存储失败返回错误。
    async fn dispatch_batch(
        &self,
        publisher: &(dyn OutboxPublisher + Sync),
        limit: u32,
    ) -> Result<DispatchReport, OutboxStoreError> {
        PgOutbox::dispatch_batch(self, publisher, limit).await
    }

    /// 业务作用：通过后端中立合同投递 PostgreSQL global 批次并执行确定性死信裁决。
    ///
    /// 参数说明：
    /// - `publisher`：至少一次发布端。
    /// - `limit`：本轮最多领取的事件数。
    /// - `max_attempts`：进入死信集合前的确定性失败轮次上限。
    ///
    /// 返回：本轮发布报告；输入或存储失败返回错误。
    async fn dispatch_batch_with_dlt(
        &self,
        publisher: &(dyn OutboxPublisher + Sync),
        limit: u32,
        max_attempts: u32,
    ) -> Result<DispatchReport, OutboxStoreError> {
        PgOutbox::dispatch_batch_with_dlt(self, publisher, limit, max_attempts).await
    }

    /// 业务作用：通过后端中立合同投递 PostgreSQL 单 lane 并确认成功前缀。
    ///
    /// 参数说明：
    /// - `publisher`：至少一次发布端。
    /// - `channel`：冻结路由生成的 lane 名称。
    /// - `limit`：本轮最多领取的事件数。
    ///
    /// 返回：本轮 lane 报告；输入或存储失败返回错误。
    async fn dispatch_batch_channel(
        &self,
        publisher: &(dyn OutboxPublisher + Sync),
        channel: &str,
        limit: u32,
    ) -> Result<DispatchReport, OutboxStoreError> {
        PgOutbox::dispatch_batch_channel(self, publisher, channel, limit).await
    }

    /// 业务作用：通过后端中立合同投递 PostgreSQL 单 lane 并执行确定性死信裁决。
    ///
    /// 参数说明：
    /// - `publisher`：至少一次发布端。
    /// - `channel`：冻结路由生成的 lane 名称。
    /// - `limit`：本轮最多领取的事件数。
    /// - `max_attempts`：进入死信集合前的确定性失败轮次上限。
    ///
    /// 返回：本轮 lane 报告；输入或存储失败返回错误。
    async fn dispatch_batch_channel_with_dlt(
        &self,
        publisher: &(dyn OutboxPublisher + Sync),
        channel: &str,
        limit: u32,
        max_attempts: u32,
    ) -> Result<DispatchReport, OutboxStoreError> {
        PgOutbox::dispatch_batch_channel_with_dlt(self, publisher, channel, limit, max_attempts)
            .await
    }

    /// 业务作用：通过后端中立合同读取 PostgreSQL 单 lane 积压。
    ///
    /// 参数说明：
    /// - `channel`：待观测的 lane 名称。
    ///
    /// 返回：该 lane 的非负积压数；输入或数据库失败返回错误。
    async fn pending_count_channel(&self, channel: &str) -> Result<u64, OutboxStoreError> {
        PgOutbox::pending_count_channel(self, channel).await
    }
}

#[async_trait::async_trait]
impl DurableOutboxQuota for PgOutbox {
    /// 业务作用：通过后端中立合同读取 PostgreSQL 租户在飞账本。
    ///
    /// 参数说明：
    /// - `tenant`：受信租户身份。
    ///
    /// 返回：账本不存在时为零；输入或数据库失败返回错误。
    async fn tenant_quota_usage(&self, tenant: &str) -> Result<u64, OutboxStoreError> {
        PgOutbox::outbox_tenant_quota_usage(self, tenant).await
    }

    /// 业务作用：通过后端中立合同在同源 PostgreSQL 事务内对账租户在飞数。
    ///
    /// 参数说明：
    /// - `tenant`：受信租户身份。
    ///
    /// 返回：对账后的在飞数；事务或数据库失败返回错误。
    async fn reconcile_tenant_quota(&self, tenant: &str) -> Result<u64, OutboxStoreError> {
        PgOutbox::reconcile_outbox_tenant_quota(self, tenant).await
    }
}

#[async_trait::async_trait]
impl DurableOutboxRetention for PgOutbox {
    /// 业务作用：通过后端中立合同执行 PostgreSQL 有界归档与保留清理轮次。
    ///
    /// 参数说明：
    /// - `policy`：冻结保留策略。
    /// - `archive`：需要收据时提供的幂等归档端。
    /// - `now_ms`：统一 epoch 毫秒时钟。
    ///
    /// 返回：只包含已确认提交事实的报告；策略或存储失败返回错误。
    async fn retention_round(
        &self,
        policy: &OutboxRetentionPolicy,
        archive: Option<&(dyn OutboxArchive + Sync)>,
        now_ms: i64,
    ) -> Result<RetentionRoundReport, OutboxStoreError> {
        PgOutbox::retention_round(self, policy, archive, now_ms).await
    }
}

impl DurableOutboxWakeup for PgOutbox {
    /// 业务作用：通过后端中立合同订阅 PostgreSQL 已确认提交代际。
    ///
    /// 参数说明：
    /// - `channel`：指定 lane 时隔离唤醒；未指定时订阅当前 datasource 的全局代际。
    ///
    /// 返回：当前进程共享的 watch 接收端；数据库轮询仍承担最终收敛。
    fn subscribe_committed_appends(&self, channel: Option<&str>) -> watch::Receiver<u64> {
        PgOutbox::subscribe_committed_appends(self, channel)
    }
}
