[package]
name = "naopenapi"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "NASA OpenAPI 3.1 deterministic contract generator"
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
serde_json = "1"
