-- 业务作用：创建 PostgreSQL Orchestrator 所需的 Saga 状态、治理、审计与定时器持久结构。
CREATE TABLE IF NOT EXISTS saga_instance (
    saga_id VARCHAR(256) PRIMARY KEY,
    tenant_id VARCHAR(256) NOT NULL,
    workflow_name VARCHAR(128) NOT NULL,
    business_key VARCHAR(256) NOT NULL,
    definition_version BIGINT NOT NULL CHECK (definition_version > 0),
    definition_digest CHAR(64) NOT NULL,
    start_request_digest CHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    control_state VARCHAR(16) NOT NULL,
    control_version BIGINT NOT NULL CHECK (control_version > 0),
    direction VARCHAR(16) NOT NULL,
    current_step VARCHAR(128),
    compensation_plan_version CHAR(64),
    version BIGINT NOT NULL CHECK (version > 0),
    deadline_at BIGINT,
    failure_code VARCHAR(64),
    traceparent VARCHAR(55),
    paused_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT saga_instance_business_key UNIQUE (tenant_id, workflow_name, business_key)
);

CREATE TABLE IF NOT EXISTS saga_step (
    saga_id VARCHAR(256) NOT NULL,
    step_name VARCHAR(128) NOT NULL,
    ordinal BIGINT NOT NULL CHECK (ordinal > 0),
    forward_status VARCHAR(32) NOT NULL,
    cancel_status VARCHAR(32) NOT NULL,
    compensation_status VARCHAR(32) NOT NULL,
    resolution_status VARCHAR(32) NOT NULL,
    execute_effect_id CHAR(36),
    execute_command_id CHAR(36),
    execute_attempt BIGINT,
    cancel_effect_id CHAR(36),
    cancel_command_id CHAR(36),
    cancel_attempt BIGINT,
    compensate_effect_id CHAR(36),
    compensate_command_id CHAR(36),
    compensate_attempt BIGINT,
    resolve_effect_id CHAR(36),
    resolve_command_id CHAR(36),
    resolve_attempt BIGINT,
    compensation_plan_version CHAR(64),
    compensation_order BIGINT,
    last_error_code VARCHAR(64),
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    PRIMARY KEY (saga_id, step_name)
);

CREATE TABLE IF NOT EXISTS saga_step_attempt (
    saga_id VARCHAR(256) NOT NULL,
    step_name VARCHAR(128) NOT NULL,
    phase VARCHAR(16) NOT NULL,
    attempt_no BIGINT NOT NULL CHECK (attempt_no > 0),
    effect_id CHAR(36) NOT NULL,
    command_id CHAR(36) NOT NULL,
    status VARCHAR(32) NOT NULL,
    outcome_event_id VARCHAR(190),
    started_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    finished_at TIMESTAMPTZ,
    PRIMARY KEY (saga_id, step_name, phase, attempt_no),
    CONSTRAINT saga_step_attempt_effect UNIQUE (effect_id, attempt_no),
    CONSTRAINT saga_step_attempt_command UNIQUE (command_id)
);

CREATE TABLE IF NOT EXISTS saga_transition (
    saga_id VARCHAR(256) NOT NULL,
    transition_seq BIGINT NOT NULL CHECK (transition_seq > 0),
    from_state VARCHAR(32) NOT NULL,
    to_state VARCHAR(32) NOT NULL,
    trigger_kind VARCHAR(8) NOT NULL,
    trigger_id VARCHAR(190) NOT NULL,
    definition_version BIGINT NOT NULL CHECK (definition_version > 0),
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    PRIMARY KEY (saga_id, transition_seq),
    CONSTRAINT saga_transition_trigger UNIQUE (saga_id, trigger_kind, trigger_id)
);

CREATE TABLE IF NOT EXISTS saga_control_transition (
    saga_id VARCHAR(256) NOT NULL,
    control_seq BIGINT NOT NULL CHECK (control_seq > 0),
    from_state VARCHAR(16) NOT NULL,
    to_state VARCHAR(16) NOT NULL,
    operation_id VARCHAR(190) NOT NULL,
    actor VARCHAR(128) NOT NULL,
    reason VARCHAR(512) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    PRIMARY KEY (saga_id, control_seq),
    CONSTRAINT saga_control_operation UNIQUE (saga_id, operation_id)
);

CREATE TABLE IF NOT EXISTS saga_management_audit (
    saga_id VARCHAR(256) NOT NULL,
    operation_id VARCHAR(190) NOT NULL,
    action VARCHAR(64) NOT NULL,
    actor VARCHAR(128) NOT NULL,
    reason VARCHAR(512) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    PRIMARY KEY (saga_id, operation_id)
);

CREATE TABLE IF NOT EXISTS saga_conflict_fact (
    saga_id VARCHAR(256) NOT NULL,
    incoming_event_id VARCHAR(190) NOT NULL,
    step_name VARCHAR(128) NOT NULL,
    phase VARCHAR(16) NOT NULL,
    attempt_no BIGINT NOT NULL CHECK (attempt_no > 0),
    existing_status VARCHAR(32) NOT NULL,
    incoming_status VARCHAR(32) NOT NULL,
    conflict_kind VARCHAR(64) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    PRIMARY KEY (saga_id, incoming_event_id)
);

-- 同一 Saga 的 guard 行在事务内递增并持锁到提交，避免 identity 预分配造成审计游标跳项。
CREATE TABLE IF NOT EXISTS saga_audit_stream_guard (
    saga_id VARCHAR(256) PRIMARY KEY,
    generation BIGINT NOT NULL CHECK (generation > 0)
);

-- 跨类别审计事实使用同一个数据库序号；attempt 的开始与终态变化各自形成不可变快照。
CREATE TABLE IF NOT EXISTS saga_audit_event (
    audit_seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    saga_id VARCHAR(256) NOT NULL,
    record_kind VARCHAR(16) NOT NULL,
    event_identity VARCHAR(512) NOT NULL,
    event_revision VARCHAR(256) NOT NULL,
    step_name VARCHAR(128),
    phase VARCHAR(16),
    attempt_no BIGINT,
    effect_id CHAR(36),
    command_id CHAR(36),
    attempt_status VARCHAR(32),
    outcome_event_id VARCHAR(190),
    transition_seq BIGINT,
    from_state VARCHAR(32),
    to_state VARCHAR(32),
    trigger_kind VARCHAR(8),
    trigger_id VARCHAR(190),
    definition_version BIGINT,
    control_seq BIGINT,
    operation_id VARCHAR(190),
    action VARCHAR(64),
    actor VARCHAR(128),
    reason VARCHAR(512),
    incoming_event_id VARCHAR(190),
    existing_status VARCHAR(32),
    incoming_status VARCHAR(32),
    conflict_kind VARCHAR(64),
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT saga_audit_event_revision
        UNIQUE (saga_id, record_kind, event_identity, event_revision)
);

-- 回填只能依赖已验证的逻辑唯一约束；同名对象缺失或列顺序漂移时必须在数据库代码收敛前停止。
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint AS constraint_contract
        WHERE constraint_contract.conrelid = 'saga_audit_event'::regclass
          AND constraint_contract.conname = 'saga_audit_event_revision'
          AND constraint_contract.contype = 'u'
          AND constraint_contract.convalidated
          AND constraint_contract.conkey = ARRAY[
              (SELECT attnum FROM pg_attribute
               WHERE attrelid = 'saga_audit_event'::regclass AND attname = 'saga_id'),
              (SELECT attnum FROM pg_attribute
               WHERE attrelid = 'saga_audit_event'::regclass AND attname = 'record_kind'),
              (SELECT attnum FROM pg_attribute
               WHERE attrelid = 'saga_audit_event'::regclass AND attname = 'event_identity'),
              (SELECT attnum FROM pg_attribute
               WHERE attrelid = 'saga_audit_event'::regclass AND attname = 'event_revision')
          ]::SMALLINT[]
    ) THEN
        RAISE EXCEPTION 'Saga audit event revision constraint is invalid';
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS saga_timer (
    saga_id VARCHAR(256) NOT NULL,
    scope_kind VARCHAR(8) NOT NULL,
    scope_key VARCHAR(128) NOT NULL,
    kind VARCHAR(64) NOT NULL,
    attempt_no BIGINT NOT NULL CHECK (attempt_no > 0),
    timer_id VARCHAR(190) NOT NULL,
    due_at BIGINT NOT NULL,
    available_at BIGINT NOT NULL,
    state VARCHAR(16) NOT NULL,
    expected_saga_version BIGINT NOT NULL CHECK (expected_saga_version > 0),
    generation BIGINT NOT NULL CHECK (generation > 0),
    owner VARCHAR(128),
    fencing_token VARCHAR(64),
    claimed_until BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    PRIMARY KEY (saga_id, scope_kind, scope_key, kind, attempt_no),
    CONSTRAINT saga_timer_identity UNIQUE (timer_id)
);

CREATE TABLE IF NOT EXISTS saga_tenant_quota (
    tenant_id VARCHAR(256) NOT NULL,
    in_flight BIGINT NOT NULL DEFAULT 0 CHECK (in_flight >= 0),
    initialized BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    PRIMARY KEY (tenant_id)
);

CREATE TABLE IF NOT EXISTS saga_tenant_action_rate (
    tenant_id VARCHAR(256) NOT NULL,
    window_start_ms BIGINT NOT NULL CHECK (window_start_ms >= 0),
    used BIGINT NOT NULL DEFAULT 0 CHECK (used >= 0),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    PRIMARY KEY (tenant_id, window_start_ms)
);

-- 业务作用：在配额账本更新时记录数据库提交侧时间，供治理状态观测与诊断使用。
CREATE OR REPLACE FUNCTION nasaga_set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = clock_timestamp();
    RETURN NEW;
END
$$;

-- 业务作用：在 attempt 创建时追加不可变审计事件；事实表与事件表任一写入失败都会阻止业务事实提交。
CREATE OR REPLACE FUNCTION nasaga_audit_attempt_insert()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    -- 先递增所属 Saga 的提交栅栏，再分配 identity 序号，后继事件不能越过未提交前驱。
    INSERT INTO saga_audit_stream_guard (saga_id, generation) VALUES (NEW.saga_id, 1)
    ON CONFLICT (saga_id) DO UPDATE
        SET generation = saga_audit_stream_guard.generation + 1;
    INSERT INTO saga_audit_event
        (saga_id, record_kind, event_identity, event_revision, step_name, phase, attempt_no,
         effect_id, command_id, attempt_status, outcome_event_id, occurred_at)
    VALUES
        (NEW.saga_id, 'attempt', concat_ws(chr(31), NEW.step_name, NEW.phase, NEW.attempt_no),
         'started', NEW.step_name, NEW.phase, NEW.attempt_no, NEW.effect_id, NEW.command_id,
         NEW.status, NEW.outcome_event_id, NEW.started_at)
    ON CONFLICT DO NOTHING;
    RETURN NEW;
END
$$;

-- 业务作用：将 attempt 的后续状态变化追加为新事件，避免原地更新越过已发出的审计游标。
CREATE OR REPLACE FUNCTION nasaga_audit_attempt_update()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    -- attempt 原地变化与其它事实共用 Saga 提交栅栏，断线游标不会跳过迟提交事务。
    INSERT INTO saga_audit_stream_guard (saga_id, generation) VALUES (NEW.saga_id, 1)
    ON CONFLICT (saga_id) DO UPDATE
        SET generation = saga_audit_stream_guard.generation + 1;
    INSERT INTO saga_audit_event
        (saga_id, record_kind, event_identity, event_revision, step_name, phase, attempt_no,
         effect_id, command_id, attempt_status, outcome_event_id, occurred_at)
    VALUES
        (NEW.saga_id, 'attempt', concat_ws(chr(31), NEW.step_name, NEW.phase, NEW.attempt_no),
         concat_ws(chr(31), 'status', NEW.status, COALESCE(NEW.outcome_event_id, '')),
         NEW.step_name, NEW.phase, NEW.attempt_no, NEW.effect_id, NEW.command_id, NEW.status,
         NEW.outcome_event_id, COALESCE(NEW.finished_at, clock_timestamp()))
    ON CONFLICT DO NOTHING;
    RETURN NEW;
END
$$;

-- 业务作用：将实例状态迁移按数据库提交顺序追加到统一审计流。
CREATE OR REPLACE FUNCTION nasaga_audit_transition_insert()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    -- 先取得 Saga guard 权威再分配序号，保持事务提交与审计可见顺序一致。
    INSERT INTO saga_audit_stream_guard (saga_id, generation) VALUES (NEW.saga_id, 1)
    ON CONFLICT (saga_id) DO UPDATE
        SET generation = saga_audit_stream_guard.generation + 1;
    INSERT INTO saga_audit_event
        (saga_id, record_kind, event_identity, event_revision, transition_seq, from_state,
         to_state, trigger_kind, trigger_id, definition_version, occurred_at)
    VALUES
        (NEW.saga_id, 'transition', NEW.transition_seq::text, 'fact', NEW.transition_seq,
         NEW.from_state, NEW.to_state, NEW.trigger_kind, NEW.trigger_id, NEW.definition_version,
         NEW.occurred_at)
    ON CONFLICT DO NOTHING;
    RETURN NEW;
END
$$;

-- 业务作用：将控制面状态变化按数据库提交顺序追加到统一审计流。
CREATE OR REPLACE FUNCTION nasaga_audit_control_insert()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    -- 控制操作必须在 Saga 提交栅栏内进入审计流，避免后继操作先被游标观察。
    INSERT INTO saga_audit_stream_guard (saga_id, generation) VALUES (NEW.saga_id, 1)
    ON CONFLICT (saga_id) DO UPDATE
        SET generation = saga_audit_stream_guard.generation + 1;
    INSERT INTO saga_audit_event
        (saga_id, record_kind, event_identity, event_revision, control_seq, from_state, to_state,
         operation_id, actor, reason, occurred_at)
    VALUES
        (NEW.saga_id, 'control', NEW.operation_id, 'fact', NEW.control_seq, NEW.from_state,
         NEW.to_state, NEW.operation_id, NEW.actor, NEW.reason, NEW.occurred_at)
    ON CONFLICT DO NOTHING;
    RETURN NEW;
END
$$;

-- 业务作用：将管理操作事实按数据库提交顺序追加到统一审计流。
CREATE OR REPLACE FUNCTION nasaga_audit_management_insert()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    -- 管理操作先锁定 Saga 提交栅栏，确保同一实例的 audit_seq 不发生可见性倒序。
    INSERT INTO saga_audit_stream_guard (saga_id, generation) VALUES (NEW.saga_id, 1)
    ON CONFLICT (saga_id) DO UPDATE
        SET generation = saga_audit_stream_guard.generation + 1;
    INSERT INTO saga_audit_event
        (saga_id, record_kind, event_identity, event_revision, operation_id, action, actor,
         reason, occurred_at)
    VALUES
        (NEW.saga_id, 'management', NEW.operation_id, 'fact', NEW.operation_id, NEW.action,
         NEW.actor, NEW.reason, NEW.occurred_at)
    ON CONFLICT DO NOTHING;
    RETURN NEW;
END
$$;

-- 业务作用：将冲突事实按数据库提交顺序追加到统一审计流。
CREATE OR REPLACE FUNCTION nasaga_audit_conflict_insert()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    -- 冲突证据先取得 Saga 提交栅栏，较新的审计事实不能越过尚未提交的冲突。
    INSERT INTO saga_audit_stream_guard (saga_id, generation) VALUES (NEW.saga_id, 1)
    ON CONFLICT (saga_id) DO UPDATE
        SET generation = saga_audit_stream_guard.generation + 1;
    INSERT INTO saga_audit_event
        (saga_id, record_kind, event_identity, event_revision, incoming_event_id, step_name,
         phase, attempt_no, existing_status, incoming_status, conflict_kind, occurred_at)
    VALUES
        (NEW.saga_id, 'conflict', NEW.incoming_event_id, 'fact', NEW.incoming_event_id,
         NEW.step_name, NEW.phase, NEW.attempt_no, NEW.existing_status, NEW.incoming_status,
         NEW.conflict_kind, NEW.occurred_at)
    ON CONFLICT DO NOTHING;
    RETURN NEW;
END
$$;

DROP TRIGGER IF EXISTS nasaga_instance_updated_at ON saga_instance;
CREATE TRIGGER nasaga_instance_updated_at
BEFORE UPDATE ON saga_instance
FOR EACH ROW EXECUTE FUNCTION nasaga_set_updated_at();

DROP TRIGGER IF EXISTS nasaga_timer_updated_at ON saga_timer;
CREATE TRIGGER nasaga_timer_updated_at
BEFORE UPDATE ON saga_timer
FOR EACH ROW EXECUTE FUNCTION nasaga_set_updated_at();

DROP TRIGGER IF EXISTS nasaga_audit_attempt_insert ON saga_step_attempt;
CREATE TRIGGER nasaga_audit_attempt_insert
AFTER INSERT ON saga_step_attempt
FOR EACH ROW EXECUTE FUNCTION nasaga_audit_attempt_insert();

DROP TRIGGER IF EXISTS nasaga_audit_attempt_update ON saga_step_attempt;
CREATE TRIGGER nasaga_audit_attempt_update
AFTER UPDATE ON saga_step_attempt
FOR EACH ROW EXECUTE FUNCTION nasaga_audit_attempt_update();

DROP TRIGGER IF EXISTS nasaga_audit_transition_insert ON saga_transition;
CREATE TRIGGER nasaga_audit_transition_insert
AFTER INSERT ON saga_transition
FOR EACH ROW EXECUTE FUNCTION nasaga_audit_transition_insert();

DROP TRIGGER IF EXISTS nasaga_audit_control_insert ON saga_control_transition;
CREATE TRIGGER nasaga_audit_control_insert
AFTER INSERT ON saga_control_transition
FOR EACH ROW EXECUTE FUNCTION nasaga_audit_control_insert();

DROP TRIGGER IF EXISTS nasaga_audit_management_insert ON saga_management_audit;
CREATE TRIGGER nasaga_audit_management_insert
AFTER INSERT ON saga_management_audit
FOR EACH ROW EXECUTE FUNCTION nasaga_audit_management_insert();

DROP TRIGGER IF EXISTS nasaga_audit_conflict_insert ON saga_conflict_fact;
CREATE TRIGGER nasaga_audit_conflict_insert
AFTER INSERT ON saga_conflict_fact
FOR EACH ROW EXECUTE FUNCTION nasaga_audit_conflict_insert();

BEGIN;

-- 业务作用：只冻结仍缺统一事件的 Saga；新事实已由 trigger 同事务进入事件流。
CREATE TEMPORARY TABLE nasaga_audit_backfill_saga ON COMMIT DROP AS
SELECT saga_id FROM (
    SELECT attempt.saga_id FROM saga_step_attempt AS attempt
    WHERE NOT EXISTS (
        SELECT 1 FROM saga_audit_event AS event
        WHERE event.saga_id = attempt.saga_id AND event.record_kind = 'attempt'
          AND event.event_identity = concat_ws(chr(31), attempt.step_name, attempt.phase,
              attempt.attempt_no)
          AND event.event_revision = CASE WHEN attempt.status = 'STARTED' THEN 'started'
              ELSE concat_ws(chr(31), 'status', attempt.status,
                  COALESCE(attempt.outcome_event_id, '')) END
    )
    UNION
    SELECT transition.saga_id FROM saga_transition AS transition
    WHERE NOT EXISTS (
        SELECT 1 FROM saga_audit_event AS event
        WHERE event.saga_id = transition.saga_id AND event.record_kind = 'transition'
          AND event.event_identity = transition.transition_seq::text
          AND event.event_revision = 'fact'
    )
    UNION
    SELECT control.saga_id FROM saga_control_transition AS control
    WHERE NOT EXISTS (
        SELECT 1 FROM saga_audit_event AS event
        WHERE event.saga_id = control.saga_id AND event.record_kind = 'control'
          AND event.event_identity = control.operation_id AND event.event_revision = 'fact'
    )
    UNION
    SELECT management.saga_id FROM saga_management_audit AS management
    WHERE NOT EXISTS (
        SELECT 1 FROM saga_audit_event AS event
        WHERE event.saga_id = management.saga_id AND event.record_kind = 'management'
          AND event.event_identity = management.operation_id AND event.event_revision = 'fact'
    )
    UNION
    SELECT conflict.saga_id FROM saga_conflict_fact AS conflict
    WHERE NOT EXISTS (
        SELECT 1 FROM saga_audit_event AS event
        WHERE event.saga_id = conflict.saga_id AND event.record_kind = 'conflict'
          AND event.event_identity = conflict.incoming_event_id AND event.event_revision = 'fact'
    )
) AS missing;

-- 回填读取任何存量事实前先按稳定顺序取得全部 Saga guard，并持有到事件提交；
-- 在线事务若已分配较小序号，回填必须等待其提交后再分配可见序号。
INSERT INTO saga_audit_stream_guard (saga_id, generation)
SELECT saga_id, 1 FROM nasaga_audit_backfill_saga ORDER BY saga_id
ON CONFLICT (saga_id) DO UPDATE
SET generation = saga_audit_stream_guard.generation + 1;

-- 已有数据库第一次启用统一事件流时只回填当前事实快照；唯一键保证启动重试不会复制历史。
INSERT INTO saga_audit_event
    (saga_id, record_kind, event_identity, event_revision, step_name, phase, attempt_no,
     effect_id, command_id, attempt_status, outcome_event_id, occurred_at)
SELECT saga_id, 'attempt', concat_ws(chr(31), step_name, phase, attempt_no),
    CASE WHEN status = 'STARTED' THEN 'started'
         ELSE concat_ws(chr(31), 'status', status, COALESCE(outcome_event_id, '')) END,
    step_name, phase, attempt_no, effect_id, command_id, status, outcome_event_id,
    COALESCE(finished_at, started_at)
FROM saga_step_attempt
WHERE saga_id IN (SELECT saga_id FROM nasaga_audit_backfill_saga)
ON CONFLICT DO NOTHING;

INSERT INTO saga_audit_event
    (saga_id, record_kind, event_identity, event_revision, transition_seq, from_state, to_state,
     trigger_kind, trigger_id, definition_version, occurred_at)
SELECT saga_id, 'transition', transition_seq::text, 'fact', transition_seq, from_state, to_state,
    trigger_kind, trigger_id, definition_version, occurred_at
FROM saga_transition
WHERE saga_id IN (SELECT saga_id FROM nasaga_audit_backfill_saga)
ON CONFLICT DO NOTHING;

INSERT INTO saga_audit_event
    (saga_id, record_kind, event_identity, event_revision, control_seq, from_state, to_state,
     operation_id, actor, reason, occurred_at)
SELECT saga_id, 'control', operation_id, 'fact', control_seq, from_state, to_state, operation_id,
    actor, reason, occurred_at
FROM saga_control_transition
WHERE saga_id IN (SELECT saga_id FROM nasaga_audit_backfill_saga)
ON CONFLICT DO NOTHING;

INSERT INTO saga_audit_event
    (saga_id, record_kind, event_identity, event_revision, operation_id, action, actor, reason,
     occurred_at)
SELECT saga_id, 'management', operation_id, 'fact', operation_id, action, actor, reason, occurred_at
FROM saga_management_audit
WHERE saga_id IN (SELECT saga_id FROM nasaga_audit_backfill_saga)
ON CONFLICT DO NOTHING;

INSERT INTO saga_audit_event
    (saga_id, record_kind, event_identity, event_revision, incoming_event_id, step_name, phase,
     attempt_no, existing_status, incoming_status, conflict_kind, occurred_at)
SELECT saga_id, 'conflict', incoming_event_id, 'fact', incoming_event_id, step_name, phase,
    attempt_no, existing_status, incoming_status, conflict_kind, occurred_at
FROM saga_conflict_fact
WHERE saga_id IN (SELECT saga_id FROM nasaga_audit_backfill_saga)
ON CONFLICT DO NOTHING;

COMMIT;

CREATE INDEX IF NOT EXISTS saga_instance_status_idx ON saga_instance(status);
CREATE INDEX IF NOT EXISTS saga_instance_lifecycle_idx
    ON saga_instance(status, created_at, updated_at);
CREATE INDEX IF NOT EXISTS saga_instance_tenant_saga_idx
    ON saga_instance(tenant_id, saga_id);
CREATE INDEX IF NOT EXISTS saga_instance_tenant_workflow_saga_idx
    ON saga_instance(tenant_id, workflow_name, saga_id);
CREATE INDEX IF NOT EXISTS saga_instance_tenant_created_saga_idx
    ON saga_instance(tenant_id, created_at, saga_id);
CREATE INDEX IF NOT EXISTS saga_instance_tenant_workflow_created_saga_idx
    ON saga_instance(tenant_id, workflow_name, created_at, saga_id);
CREATE INDEX IF NOT EXISTS saga_instance_tenant_status_saga_idx
    ON saga_instance(tenant_id, status, saga_id);
CREATE INDEX IF NOT EXISTS saga_instance_tenant_workflow_status_saga_idx
    ON saga_instance(tenant_id, workflow_name, status, saga_id);
CREATE INDEX IF NOT EXISTS saga_instance_tenant_status_created_saga_idx
    ON saga_instance(tenant_id, status, created_at, saga_id);
CREATE INDEX IF NOT EXISTS saga_instance_tenant_workflow_status_created_saga_idx
    ON saga_instance(tenant_id, workflow_name, status, created_at, saga_id);
CREATE STATISTICS IF NOT EXISTS saga_instance_tenant_status_stats (mcv, dependencies)
    ON tenant_id, status FROM saga_instance;
CREATE STATISTICS IF NOT EXISTS saga_instance_tenant_workflow_status_stats (mcv, dependencies)
    ON tenant_id, workflow_name, status FROM saga_instance;
CREATE INDEX IF NOT EXISTS saga_step_ordinal_idx ON saga_step(saga_id, ordinal);
CREATE INDEX IF NOT EXISTS saga_attempt_status_idx ON saga_step_attempt(status, finished_at);
CREATE INDEX IF NOT EXISTS saga_attempt_retry_idx ON saga_step_attempt(attempt_no);
CREATE INDEX IF NOT EXISTS saga_transition_state_idx ON saga_transition(to_state, occurred_at);
CREATE INDEX IF NOT EXISTS saga_management_actor_idx
    ON saga_management_audit(actor, occurred_at);
CREATE INDEX IF NOT EXISTS saga_conflict_time_idx
    ON saga_conflict_fact(saga_id, occurred_at);
CREATE INDEX IF NOT EXISTS saga_audit_event_stream_idx
    ON saga_audit_event(saga_id, audit_seq);
CREATE INDEX IF NOT EXISTS saga_timer_due_idx ON saga_timer(state, available_at, due_at);
