[package]
name = "nasecret-http"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "NASA two-phase rotating reqwest TLS/mTLS client backed by nasecret snapshots"
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
arc-swap = "1"
async-trait = "0.1"
nasecret = { version = "1.0.0", path = "../nasecret" }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
zeroize = "1"
