# mapper —— 声明式 Mapper 运行时桥 + re-export #[Mapper]/#[Query]
[package]
name = "namapper"
version = "1.0.2"
edition.workspace = true
rust-version.workspace = true
description = "Declarative mapper runtime for SQLx and ambient transactions"
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords = ["mysql", "mapper", "sql", "database", "async"]
categories = ["database", "asynchronous"]

[lib]
name = "namapper"

[features]
default = []
grouped-cache = ["dep:cacheable"]
redis-cache = ["namapper-core/redis-cache"]

[dependencies]
namapper-core = { version = "1.0.0" }
namapper-macro = { package = "namapper-macro", version = "1.0.1" }
natx = { package = "natx", version = "1.0.3" }
sqlx = { version = "0.9", features = ["runtime-tokio", "tls-rustls", "mysql", "chrono", "json"] }
async-trait = "0.1"
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
linkme = "0.3"
async-stream = "0.3"
futures-core = "0.3"
futures-util = "0.3"
cacheable = { version = "1.0.1", optional = true }
