[package]
name = "napp-macro"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "NASA application entry attribute"
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
proc-macro = true

[dependencies]
nasa-macro-support = { package = "macro-support", version = "1.0.0", path = "../macro-support" }
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
