[package]
name = "nainbox-mysql"
version = "1.0.1"
edition.workspace = true
rust-version.workspace = true
description = "NASA Inbox MySQL backend using the ambient natx transaction"
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
anyhow = "1"
nainbox-core = { version = "1.0.0" }
natx = { version = "1.0.1" }
sqlx = { version = "0.9", features = ["runtime-tokio", "tls-rustls", "mysql"] }
